server:
  port: ${SERVER_PORT:8080}

statistic-server:
  url: ${STATISTIC_SERVER:http://localhost:9090}

spring:
  application:
    name: "ewm-main-service"
  sql:
    init:
      mode: never
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: 'true'
      ddl-auto: create
logging:
  level:
    org:
      springframework:
        transaction:
          nodeValue: INFO
          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: INFO

---
spring:
  datasource:
    url: jdbc:h2:mem:db
    username: user
    password: password
    driverClassName: org.h2.Driver
  config:
    activate:
      on-profile: ci,test